name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 coverage

      - name: Lint with flake8
        run: |
          source .venv/bin/activate
          flake8 .

      - name: Run tests with coverage
        run: |
          source .venv/bin/activate
          coverage run -m pytest --maxfail=1 --disable-warnings -q

      - name: Coverage report
        run: |
          source .venv/bin/activate
          coverage report -m
